name: Desktop Builds

on:
  push:
    branches:
      - "release/**"
  workflow_dispatch:

jobs:
  macos:
    name: macOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Ad-hoc sign macOS binary
        run: codesign --force --deep --sign - build/bin/iEngineV2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iEngineV2-macos
          path: |
            build/bin/**

  windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iEngineV2-windows
          path: |
            build/bin/**
